"""empty message

Revision ID: 0e5acda41782
Revises: 46a79787d331
Create Date: 2025-06-18 20:31:01.617081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5acda41782'
down_revision = '46a79787d331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('changes',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('changes',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
