"""add api setup

Revision ID: 32817402ef53
Revises: dcaafd65d4f0
Create Date: 2026-09-29 22:06:14.806079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32817402ef53'
down_revision = 'dcaafd65d4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_api_key_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_key_key_hash')),
    sa.UniqueConstraint('key_id', name=op.f('uq_api_key_key_id')),
    sa.UniqueConstraint('name', name=op.f('uq_api_key_name'))
    )
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available_in_clip_player', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_column('is_available_in_clip_player')

    op.drop_table('api_key')
    # ### end Alembic commands ###
