"""Increase twitch_id length

Revision ID: 348a0686efd2
Revises: dfd86c1fa927
Create Date: 2025-06-29 09:31:23.296197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '348a0686efd2'
down_revision = 'dfd86c1fa927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.alter_column('twitch_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.alter_column('twitch_id',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
