"""Add Layout table

Revision ID: 40bf69b3222a
Revises: f3f83bf865ce
Create Date: 2025-09-27 22:18:57.235643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bf69b3222a'
down_revision = 'f3f83bf865ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_layout_created_by_user')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_layout_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_layout')),
    sa.UniqueConstraint('name', name=op.f('uq_layout_name'))
    )
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clip_layout_id'), ['layout_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_clip_layout_id_layout'), 'layout', ['layout_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clip_layout_id_layout'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clip_layout_id'))
        batch_op.drop_column('layout_id')

    op.drop_table('layout')
    # ### end Alembic commands ###
