"""empty message

Revision ID: 46a79787d331
Revises: c941af130158
Create Date: 2025-06-18 20:19:11.999135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a79787d331'
down_revision = 'c941af130158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes', sa.Text(), nullable=False))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_column('changed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed', sa.TEXT(), nullable=False))
        batch_op.alter_column('action',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('changes')

    # ### end Alembic commands ###
