"""Add Statistics table

Revision ID: 5d4d5ee4da2b
Revises: d03cbda21c1c
Create Date: 2026-01-03 19:25:31.048746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4d5ee4da2b'
down_revision = 'd03cbda21c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_clips', sa.Integer(), nullable=True),
    sa.Column('unsorted_clips', sa.Integer(), nullable=True),
    sa.Column('clips_without_subjects', sa.Integer(), nullable=True),
    sa.Column('clips_without_themes', sa.Integer(), nullable=True),
    sa.Column('clips_without_category', sa.Integer(), nullable=True),
    sa.Column('clips_without_layout', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_upvotes', sa.Integer(), nullable=True),
    sa.Column('total_verified_users', sa.Integer(), nullable=True),
    sa.Column('unique_broadcasters', sa.Integer(), nullable=True),
    sa.Column('unique_clippers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistics'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
