"""empty message

Revision ID: 5dab565658bd
Revises: 71328fcdb0cb
Create Date: 2025-06-23 21:46:14.465115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dab565658bd'
down_revision = '71328fcdb0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_log_admin_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_activity_log_admin_id_user'), 'user', ['admin_id'], ['id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_updated_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_category_created_by_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_category_created_by_user'), 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_category_updated_by_user'), 'user', ['updated_by'], ['id'])

    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clip_updated_by_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_clip_updated_by_user'), 'user', ['updated_by'], ['id'])

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_constraint('fk_status_created_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_status_updated_by_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_status_updated_by_user'), 'user', ['updated_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_status_created_by_user'), 'user', ['created_by'], ['id'])

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subject_created_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_subject_updated_by_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_subject_created_by_user'), 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_subject_updated_by_user'), 'user', ['updated_by'], ['id'])

    with op.batch_alter_table('subject_category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subject_category_created_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_subject_category_updated_by_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_subject_category_updated_by_user'), 'user', ['updated_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_subject_category_created_by_user'), 'user', ['created_by'], ['id'])

    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_constraint('fk_theme_created_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_theme_updated_by_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_theme_updated_by_user'), 'user', ['updated_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_theme_created_by_user'), 'user', ['created_by'], ['id'])

    with op.batch_alter_table('upvotes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_updated_by_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_updated_by_user'), 'user', ['updated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_updated_by_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_updated_by_user', 'user', ['updated_by'], ['twitch_id'])

    with op.batch_alter_table('upvotes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_theme_created_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_theme_updated_by_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_theme_updated_by_user', 'user', ['updated_by'], ['twitch_id'])
        batch_op.create_foreign_key('fk_theme_created_by_user', 'user', ['created_by'], ['twitch_id'])

    with op.batch_alter_table('subject_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subject_category_created_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_subject_category_updated_by_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_subject_category_updated_by_user', 'user', ['updated_by'], ['twitch_id'])
        batch_op.create_foreign_key('fk_subject_category_created_by_user', 'user', ['created_by'], ['twitch_id'])

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subject_updated_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_subject_created_by_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_subject_updated_by_user', 'user', ['updated_by'], ['twitch_id'])
        batch_op.create_foreign_key('fk_subject_created_by_user', 'user', ['created_by'], ['twitch_id'])

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_status_created_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_status_updated_by_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_status_updated_by_user', 'user', ['updated_by'], ['twitch_id'])
        batch_op.create_foreign_key('fk_status_created_by_user', 'user', ['created_by'], ['twitch_id'])

    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clip_updated_by_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_clip_updated_by_user', 'user', ['updated_by'], ['twitch_id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_category_updated_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_category_created_by_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_category_created_by_user', 'user', ['created_by'], ['twitch_id'])
        batch_op.create_foreign_key('fk_category_updated_by_user', 'user', ['updated_by'], ['twitch_id'])

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_log_admin_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_activity_log_admin_id_user', 'user', ['admin_id'], ['twitch_id'])

    # ### end Alembic commands ###
