"""empty message

Revision ID: 71328fcdb0cb
Revises: 61b4b362ca17
Create Date: 2025-06-23 19:42:33.118613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71328fcdb0cb'
down_revision = '61b4b362ca17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.alter_column('broadcaster_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('creator_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('twitch_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('twitch_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('broadcaster_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
