"""Update User table

Revision ID: dcaafd65d4f0
Revises: 5d4d5ee4da2b
Create Date: 2026-03-08 11:32:54.004904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcaafd65d4f0'
down_revision = '5d4d5ee4da2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
        batch_op.alter_column('profile_image_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
        batch_op.drop_index('ix_user_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_login', ['login'], unique=False)
        batch_op.alter_column('profile_image_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
        batch_op.alter_column('login',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               nullable=False)

    # ### end Alembic commands ###
