"""Initial migration

Revision ID: dfd86c1fa927
Revises: 
Create Date: 2025-06-28 14:17:18.883019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd86c1fa927'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rank'))
    )
    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rank_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('profile_image_url', sa.String(length=256), nullable=False),
    sa.Column('contributions', sa.Integer(), nullable=False),
    sa.Column('last_verified', sa.DateTime(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('refresh_token', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('login_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['rank.id'], name=op.f('fk_user_rank_id_rank')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_user_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_display_name'), ['display_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_rank_id'), ['rank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_twitch_id'), ['twitch_id'], unique=True)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=32), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('row_name', sa.String(length=32), nullable=True),
    sa.Column('row_twitch_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('fk_activity_log_admin_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_category_created_by_user')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_category_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('Visible', 'Pending', 'Hidden', name='status_types'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_status_created_by_user')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_status_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status')),
    sa.UniqueConstraint('name', name=op.f('uq_status_name'))
    )
    op.create_table('subject_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_subject_category_created_by_user')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_subject_category_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_category')),
    sa.UniqueConstraint('name', name=op.f('uq_subject_category_name'))
    )
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_theme_created_by_user')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_theme_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theme')),
    sa.UniqueConstraint('name', name=op.f('uq_theme_name'))
    )
    op.create_table('clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('embed_url', sa.String(length=128), nullable=False),
    sa.Column('broadcaster_id', sa.Integer(), nullable=False),
    sa.Column('broadcaster_name', sa.String(length=32), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('creator_name', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('game_id', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('title_override', sa.String(length=256), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('vod_offset', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_clip_category_id_category')),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_clip_status_id_status')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_clip_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clip')),
    sa.UniqueConstraint('twitch_id', name=op.f('uq_clip_twitch_id'))
    )
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_broadcaster_name'), ['broadcaster_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_creator_name'), ['creator_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_status_id'), ['status_id'], unique=False)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('subtext', sa.String(length=32), nullable=True),
    sa.Column('keywords', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['subject_category.id'], name=op.f('fk_subject_category_id_subject_category')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_subject_created_by_user')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_subject_updated_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject')),
    sa.UniqueConstraint('name', name=op.f('uq_subject_name'))
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_category_id'), ['category_id'], unique=False)

    op.create_table('clip_subjects',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], name=op.f('fk_clip_subjects_clip_id_clip')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_clip_subjects_subject_id_subject')),
    sa.PrimaryKeyConstraint('clip_id', 'subject_id', name=op.f('pk_clip_subjects'))
    )
    op.create_table('clip_themes',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], name=op.f('fk_clip_themes_clip_id_clip')),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], name=op.f('fk_clip_themes_theme_id_theme')),
    sa.PrimaryKeyConstraint('clip_id', 'theme_id', name=op.f('pk_clip_themes'))
    )
    op.create_table('upvotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], name=op.f('fk_upvotes_clip_id_clip')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_upvotes_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'clip_id', name=op.f('pk_upvotes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvotes')
    op.drop_table('clip_themes')
    op.drop_table('clip_subjects')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_category_id'))

    op.drop_table('subject')
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_status_id'))
        batch_op.drop_index(batch_op.f('ix_clip_creator_name'))
        batch_op.drop_index(batch_op.f('ix_clip_category_id'))
        batch_op.drop_index(batch_op.f('ix_clip_broadcaster_name'))

    op.drop_table('clip')
    op.drop_table('theme')
    op.drop_table('subject_category')
    op.drop_table('status')
    op.drop_table('category')
    op.drop_table('activity_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_twitch_id'))
        batch_op.drop_index(batch_op.f('ix_user_rank_id'))
        batch_op.drop_index(batch_op.f('ix_user_login'))
        batch_op.drop_index(batch_op.f('ix_user_display_name'))

    op.drop_table('user')
    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rank_name'))

    op.drop_table('rank')
    # ### end Alembic commands ###
