"""Add token expiration and scope tracking

Revision ID: f863666fef24
Revises: 40bf69b3222a
Create Date: 2025-11-30 19:52:44.319150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f863666fef24'
down_revision = '40bf69b3222a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('token_scope', sa.String(length=256), nullable=True))
        batch_op.alter_column('last_verified',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_verified',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('token_scope')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
