"""empty message

Revision ID: f9fcfff16f16
Revises: f5a2d04537ed
Create Date: 2025-06-18 19:10:16.430603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fcfff16f16'
down_revision = 'f5a2d04537ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('row_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.Enum('Create', 'Update', 'Delete', name='action_types'), nullable=False),
    sa.Column('changed', sa.String(length=256), nullable=False),
    sa.Column('admin_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.twitch_id'], name=op.f('fk_activity_log_admin_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.drop_table('activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=6), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('changed', sa.VARCHAR(length=256), nullable=False),
    sa.Column('admin_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.twitch_id'], name='fk_activity_admin_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_activity')
    )
    op.drop_table('activity_log')
    # ### end Alembic commands ###
