"""empty message

Revision ID: febe04cc5d4d
Revises: 0e5acda41782
Create Date: 2025-06-18 20:36:38.628536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febe04cc5d4d'
down_revision = '0e5acda41782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('row_twitch_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('row_twitch_id')
        batch_op.drop_column('row_name')

    # ### end Alembic commands ###
